version: "3.8"

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    #    image: arm64v8/mysql:latest
    restart: unless-stopped
    container_name: mysqldb
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

#  phpmyadmin:
#    depends_on:
#      - mysqldb
#    image: phpmyadmin
#    restart: always
#    ports:
#      - "8090:80"
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: admin

  ecommerce-service:
    depends_on:
      - mysqldb
    container_name: ecommerce-service
    build: ./ecommerce-service
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "server.port" : "$SPRING_DOCKER_PORT",
            "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "org.jobrunr.background-job-server.enabled" : "true",
            "org.jobrunr.dashboard.enabled" : "true"
          }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
